### ISSUE TITLE
可不可以提供一下这3个文件

### ISSUE THREAD

**Issue by EdwinIZ8** [emoose/xvdtool#11]
### **问题描述（Description）：**
Warning: rsa3_key.bin file not found and unable to retrieve key from SDK files, you will be unable to resign packages.
Warning: odk_key.bin file not found and unable to retrieve key from SDK files, you will be unable to decrypt XVDs.
Warning: cik_keys.bin file not found and unable to retrieve key from SDK files, you will be unable to decrypt XVCs.

Decrypting package using "TestODK" key...
Error during decryption!

### **可不可以提供一下这3个文件（What I want）：**
rsa3_key.bin
odk_key.bin
cik_keys.bin

**Comment by tuxuser** [comment]
See issue #4 __Cant get keys to extract__

**Comment by emoose** [comment]
Can't provide those files, but like tuxuser said in #4 the Win10 "Microsoft Gaming Services" pack includes DLLs they can be extracted from: https://www.microsoft.com/en-us/p/gaming-services/9mwpm2cqnlhn

**Comment by EdwinIZ8** [comment]
> Can't provide those files, but like tuxuser said in #4 the Win10 "Microsoft Gaming Services" pack includes DLLs they can be extracted from: https://www.microsoft.com/en-us/p/gaming-services/9mwpm2cqnlhn

Thanks for your replying. But something is wrong with the UWP application you mentioned, the setup button is grey.

**Comment by tuxuser** [comment]
Your windows build is too old to install it. Maybe you can find an appx somewhere

**Comment by tuxuser** [comment]
Your windows build is too old to install it, see __System requirements__

**Comment by EdwinIZ8** [comment]
> Your windows build is too old to install it, see System requirements

Thanks, it works now. Now I have extracted keys by using DurangoKeyExtractor. But it said "No desired signkey provided, falling back to RedXvdPrivateKey". What's wrong?
