### ISSUE TITLE
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'xsapi.dll' or one of its dependencies: The specified module could not be found.

### ISSUE THREAD

**Issue by 0x14307** [emoose/xvdtool#34]
I am looking to mounting an XVD file I have however I get this error. Is there any way I can resolve this?

**Comment by davFaithid** [comment]
Sometimes Windows doesn't have a lot of really important libraries that many software need to function. I think this a case of that.
You can compile [this api](https://docs.microsoft.com/en-us/gaming/xbox-live/get-started/setup-ide/managed-partners/vstudio-xbox/live-compile-xdk-xbl-api-source) and place the dll in the directory of XVDTool, and it should work. 
Elsewise, there is probably an installer or direct download on microsoft's website packaging it in with a runtime.

**Comment by tuxuser** [comment]
Thx for your input @davFaithid, however in this case it is not the correct DLL.

You need to download & install the following on your windows 10 machine: https://www.microsoft.com/en-us/p/gaming-services/9mwpm2cqnlhn?activetab=pivot:overviewtab

**Comment by 0x14307** [comment]
I installed the services application however the error still occurs within the application. Would I have to find the dll & put it in a specific directory by any chance?

**Comment by tuxuser** [comment]
Normally that's not needed iirc.
Have you tried rebooting? If that does not fix it, yes, try to place it next to the executable.

**Comment by 0x14307** [comment]
I have rebooted so I'll try placing the DLL in the path of XVDTool to see if that works

**Comment by 0x14307** [comment]
Alright just tried it with xsapi in the folder of XVD however I get this now:
The application to execute does not exist: 'C:\Users\User\AppData\Local\Temp\.net\XVDTool\vzbb0gdl.ipz\XVDTool.dll'.

**Comment by 0x14307** [comment]
Quick update. Just deleted the files in my temp & now I think I'm getting closer to actually mounting this.
The following now shows:
"XvdOpenAdapter failed. Result: 0x80070002
Mounting D:\Xbone\disk.xvd failed with error"

**Comment by tuxuser** [comment]
Are you executing cmd.exe with admin privileges?

**Comment by 0x14307** [comment]
No I am not

**Comment by davFaithid** [comment]
I tried mounting updater.xvd using cmd.exe with admin priviledges and I got the following:
```
XVDTool -m -mp "X:" updater.xvd
XVDTool 0.53.0-5737d20: XVD file manipulator

Loaded key XvdSigningKey from C:\Users\davfa\AppData\Local\xvdtool\XvdSigningKey\GreenGamesPublicKey.rsa
Loaded key XvdSigningKey from C:\Users\davfa\AppData\Local\xvdtool\XvdSigningKey\GreenXvdPublicKey.rsa
Loaded key XvdSigningKey from C:\Users\davfa\AppData\Local\xvdtool\XvdSigningKey\RedXvdPrivateKey.rsa
Loaded key Odk from C:\Users\davfa\AppData\Local\xvdtool\Odk\RedOdk.odk
Loaded key Cik from C:\Users\davfa\AppData\Local\xvdtool\Cik\33ec8436-5a0e-4f0d-b1ce-3f29c3955039.cik
No desired signkey provided, falling back to RedXvdPrivateKey
No desired CIK provided, falling back to 33ec8436-5a0e-4f0d-b1ce-3f29c3955039
No desired or invalid ODK provided, will try to use ODK indicated by XVD header
Using Xvd Signkey: RedXvdPrivateKey
Using CIK: 33ec8436-5a0e-4f0d-b1ce-3f29c3955039

XvdOpenAdapter failed. Result: 0xD0000185
Mounting updater.xvd failed with error
```
