### ISSUE TITLE
Install msixvc on Windows

### ISSUE THREAD

**Issue by davispuh** [emoose/xvdtool#39]
Firstly thanks for xvdtool it's great!

I'm looking how to install msixvc files, any idea?

I found that in Windows if you start downloading some game using Xbox app or Store app then in `C:\Program Files\WindowsApps\MSIXVC`  it will create 3 files for each game.

```
%InstanceGUID% - msixvc file (game's files)
%InstanceGUID%.xvs - various metadata in JSON encoded with UTF-16, contains the download source path and CIK for msixvc
%InstanceGUID%.xvi - crdi-xvc file, looks like some metadata about download progress and other unknown stuff
```

So basically you only need `%InstanceGUID%.xvs` as then you can download msixvc file, take CIK and use `XVDTool` to extract it.
Unfortunately the msixvc file I tried all extracted `.exe` are still encrypted and no idea how do decrypt those.

There is also another file called `.phf` which is JSON containing SHA256 hashes for msixvc file.
Also it looks like `-xf` doesn't extract `user data`, can use `-xu` but then you get a single file of some container (can see several file names inside and multiple file contents)

In `.xvs` file, there's `CrdPath` that looks like
```
[XBL:]\\http://xvcf1.xboxlive.com/%digit%/%SomeGUID%/%InstanceGUID%/%path_version%_%arch%__%ProductID%.msixvc,phf=http://xvcf1.xboxlive.com/%digit%/%SomeGUID%/%InstanceGUID%/%path_version%_%arch%__%ProductID%.msixvc.phf,hoh=%Base64-CIK%,sid=%GUID2%,cv=%CorrelationVector%
```
`hoh=` specifies CIK.

Here's Ruby program to get CIK out of `.xvs`. To use `-g` flag just run `XVDTool -eu` to get CIK GUID
````ruby
#!/usr/bin/env ruby
require "optparse"
require "json"
require "base64"


def guidToBin(guid)
    data = guid.split("-").pack("H*" * 5)
    data[0..3].reverse + data[4..5].reverse + data[6..7].reverse + data[8..15]
end

guid = nil
keyDir = Dir.pwd
parser = OptionParser.new do |opts|
    opts.banner = "Usage: #{$0} [options] <XVS files...>"

    opts.on("-gGUID", "--guid=GUID", "Key GUID") do |g|
        guid = g.downcase
    end

    opts.on("-o", "--output=DIR", "Output directory") do |dir|
        keyDir = dir
    end

    opts.on_tail("-h", "--help", "Prints this help") do
        $stderr.puts(opts)
        exit
    end
end

begin
    parser.parse!
rescue OptionParser::ParseError => e
    $stderr.puts(e.message)
    exit(-1)
end

parser.parse!(ARGV)

files = ARGV
if files.length.zero?
    $stderr.puts(parser)
    exit
end

if guid && !guid.match(/^[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}$/i)
    $stderr.puts("Invalid GUID: #{guid}")
    exit(-2)
end

if guid && files.length > 1
    $stderr.puts("Using only first file and ignoring rest")
    files = files.take(1)
end

files.each do |f|
    info = JSON.parse(File.read(f, mode: "rb", encoding: Encoding::UTF_16LE))
    details = Hash[info["Request"]["ActiveSource"]["CrdPath"].split(",").map { |pair| pair.include?("=") ? pair.split("=") : ["file", pair]}]
    key = Base64.decode64(details["hoh"])
    hexKey = key.unpack('H*').first
    if guid
        filename = File.join(keyDir, guid + ".cik")
        File.write(filename, guidToBin(guid) + key)
        puts "Saved to #{filename} (#{hexKey})"
    else
        puts hexKey
    end
end
````

and to validate `msixvc` checksums
```ruby
#!/usr/bin/env ruby

require "json"
require "base64"
require "digest"

files = ARGV
if files.length.zero?
    $stderr.puts("Usage: #{$0} <MSIXVC files...>")
    exit
end

files.each do |file|
    infoFile = file + ".phf"
    info = JSON.parse(File.read(infoFile))
    size = info["PieceSize"]
    pieces = info["Pieces"]
    File.open(file, "rb") do |file|
        pieces.each_with_index do |piece, i|
            file.seek(i * size)
            data = file.read(size)
            sha = Digest::SHA256.digest(data)
            shaHex = sha.unpack('H*').first
            expectedSha = Base64.decode64(piece)
            if (sha == expectedSha)
                puts("%s (Matches)" % [shaHex])
            else
                puts("%s (Invalid! Expected: %s)" % [shaHex, expectedSha.unpack('H*').first])
                break
            end
        end
    end
end
```

**Comment by tuxuser** [comment]
Are you using https://github.com/billyhulbert/XvddKeyslotUtil to dump the CIK key for the package?
Or are you saying that the actual CIK Key is contained in the json data?

**Comment by davispuh** [comment]
Yeah, I'm not using that tool, I'm extracting it from `%InstanceGUID%.xvs` file like I wrote. It seems to decrypt XVC fine but looks like there are additional layers.

I also noticed that when windows mounts/installs XVC then that folder is not opeanable from Linux
```
unsupported reparse point
```

And for regular folders game's `exe`'s are encrypted. By default Linux will say `Permission denied`  but if you mount it with `efs_raw` then you can read encrypted data, but no idea what key to use to decrypt it.

**Comment by davispuh** [comment]
I was wrong. The `hoh` inside `XVS` file isn't CIK. But same `HashOfHashes` as in `.pfh`.
The main issue is that I thought xvdtool would tell you if you used wrong key, but it happily decrypts with whatever you give it and you'll just get garbage out. But all filenames will be correct so that's why I thought it decrypted correctly as there wasn't any errors.

So now I can extract it and all data/exe looks good, can run it but it gets stuck after logo I guess something to do with DRM...

I also noticed that if I put any `exe` inside `WindowsApps` folder then it says it 
```
The APPX file can not be accessed because it is not encrypted as expected.
```

If I check encrypt it then Windows says it can't access it...

Btw for some reason when I try to create VHD I get
```
Unhandled exception. System.IO.IOException: Out of disk space
   at DiscUtils.Ntfs.ClusterBitmap.AllocateClusters(Int64 count, Int64 proposedStart, Boolean isMft, Int64 total)
   at DiscUtils.Ntfs.RawClusterStream.AllocateClusters(Int64 startVcn, Int32 count)
   at DiscUtils.Ntfs.RawClusterStream.ExpandToClusters(Int64 numVirtualClusters, NonResidentAttributeRecord extent, Boolean allocate)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.SetCapacity(Int64 value)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.BufferStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at LibXboxOne.XvdFilesystem.InitializeVhdManually(Disk vhdDisk)
   at LibXboxOne.XvdFilesystem.ConvertToVhd(String outputFile)
   at XVDTool.Program.<>c__DisplayClass4_0.<Main>g__PerformActions|1(XvdFile file)
   at XVDTool.Program.Main(String[] args)
```
But I have plenty of free space.

**Comment by tuxuser** [comment]
VHD creation and raw image extraction is buggy, gotta admit.
- Issue with VHD could be caused by a target VHD image that is too small.. iirc if the input file is XvdType.Fixed, the output VHD will be also of fixed size - likewise for XvdType.Dynamic.

Extracting the filesystem seems to be fine, as you discovered, seems an acceptable solution for now.

**Comment by davispuh** [comment]
Actually it's very simple to install, don't need to decrypt/extract anything. It doesn't work when decrypted/extracted.
But when you download encrypted msixvc then need to just run `Add-AppPackage gamefile.msixvc` (extension doesn't matter).
It will automatically download/create other 2 files but main file isn't redownloaded.

Of course it would be nice have our own installation program that could do this too but seems like a lot of work.
