### ISSUE TITLE
cant get the keys to extract

### ISSUE THREAD

**Issue by tunip3** [emoose/xvdtool#4]
i cant seem to get the keys extracted from the xdk

**Comment by Lethaltail** [comment]
yup same

**Comment by tuxuser** [comment]
A very early SDK is needed to extract the keys from.

**Comment by tuxuser** [comment]
By now, just get the Microsoft Gaming Services on Windows 10 - has the same keys inside ;)

**Comment by tunip3** [comment]
yeah

**Comment by EdwinIZ8** [comment]
> By now, just get the Microsoft Gaming Services on Windows 10 - has the same keys inside ;)

Thanks. But it seems that the UWP application doesn't work, because the setup button is grey.

**Comment by tunip3** [comment]
you need to feed the path to the xsapi dll contained in the gaming services install folder into the Durango key extractor

**Comment by tunip3** [comment]
but if the issue is with installing you need the latest insider build.
if your machine wont install the update you can try to use a vm.
