### ISSUE TITLE
[Security] Workflow build.yml is using vulnerable action gittools/actions/gitversion/setup

### ISSUE THREAD

**Issue by igibek** [emoose/xvdtool#40]
The workflow build.yml is referencing action gittools/actions/gitversion/setup using references v0.9.9. However this reference is missing the commit [90150b40fdd6c4b06d39cfd764e900cff45ccfca](https://github.com/gittools/actions/commits/90150b40fdd6c4b06d39cfd764e900cff45ccfca) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by tuxuser** [comment]
Thanks, fixed
