### ISSUE TITLE
Unable to mount file

### ISSUE THREAD

**Issue by FalschgeldFurkan** [emoose/xvdtool#41]
I'm trying to mount a file, however it results in an error message shown in this screenshot: https://i.imgur.com/74qMk9Q.png

I have installed the GameServices framework, but skipped the part where I should extract the keys. The key extractor would ask where the key files are located, to which I had no answer, so I hoped that mounting it should work fine without extracting the keys.

If the issue is caused by skipping the extraction of keys: where do I locate them? Or if it's another cause: how can I fix it? Thanks.

**Comment by tuxuser** [comment]
1) Key extraction: Search for xsapi.dll on your filesystem. Copy all the files/folders from that directory somewhere else. Point DurangoKeyExtractor there.

2) Copy xsapi.dll next to XVDTool.dll
