### ISSUE TITLE
can't decrypt xvd

### ISSUE THREAD

**Issue by star08-web** [emoose/xvdtool#43]
i want to convert xvd to vhd, so i tried to decrypting it and when i launch the command it give me a error
someone can help me please 
this is my CMD log 
C:\Users\====\Downloads\seriesx\FactoryReset\$SystemUpdate>xvdtool -eu updater.xvd
XVDTool 0.53.0-5737d20: XVD file manipulator

No desired signkey provided, falling back to RedXvdPrivateKey
No desired CIK provided, falling back to 33ec8436-5a0e-4f0d-b1ce-3f29c3955039
No desired or invalid ODK provided, will try to use ODK indicated by XVD header
Warning: Signkey could not be loaded, you will be unable to resign XVD headers!
Warning: CIK could not be loaded!

Loading file from updater.xvd...

Verifying data hashes, use -nd to disable:
Decrypting XVD using "<ODK indicated by XVD header>" key...
Unhandled exception. System.InvalidOperationException: ODK with Id 'RedOdk' is known but not loaded! Cannot crypt CIK in header
   at LibXboxOne.XvdFile.CryptHeaderCik(Boolean encrypt)
   at LibXboxOne.XvdFile.Decrypt()
   at XVDTool.Program.<>c__DisplayClass4_0.<Main>g__PerformActions|1(XvdFile file)
   at XVDTool.Program.Main(String[] args)

**Comment by itayalush** [comment]
You need to publish this question on other sites, because no one answers, or... someone just needs to see this.

**Comment by tuxuser** [comment]
@itayalush yeah right

@star08-web `ODK with Id 'RedOdk' is known but not loaded!` - It knows that the xvd requires the RedOdk, but you don't have the RedOdk keyfile for XVDTool to find/use it.

You might wanna look into using `DurangoKeyExtractor`
