### ISSUE TITLE
system.xvd not extracting

### ISSUE THREAD

**Issue by itayalush** [emoose/xvdtool#48]
When I try to extract the system.xvd file using:
> XVDTool -xf .\System "C:\Blah\Blah\Blah\system.xvd"

It says:
> Extracting XVD files to folder "System"...
Extracted files successfully.

But doesn't even extract.
Can someone please help?

**Comment by itayalush** [comment]
@emoose Please upgrade this tool and make it easier.

**Comment by tuxuser** [comment]
The tool is targeted exclusively at developers
