### ISSUE TITLE
DurangoKeyExtractor dont finish

### ISSUE THREAD

**Issue by UseUser123321** [emoose/xvdtool#51]
The program included with this, named "DurangoKeyExtractor", is stuck at an screen like this:

![image](https://user-images.githubusercontent.com/95658122/205743145-88f4986a-5952-4da1-932a-7cd48b4e1f93.png)

**Comment by tuxuser** [comment]
You misunderstand the tool.. you have to provide it a file path where *.dll/*.sys file is located (from Microsoft Gaming Services). It will scan the file for known keys (by SHA256 Hash) and extract any that are found.

Try xvdd.sys or *.dll/*.exe of GamingServices

**Comment by UseUser123321** [comment]
Ok thank you so much.

**Comment by UseUser123321** [comment]
> You misunderstand the tool.. you have to provide it a file path where _.dll/_.sys file is located (from Microsoft Gaming Services). It will scan the file for known keys (by SHA256 Hash) and extract any that are found.
> 
> Try xvdd.sys or _.dll/_.exe of GamingServices

were do i find the files?

**Comment by davFaithid** [comment]
> > You misunderstand the tool.. you have to provide it a file path where _.dll/_.sys file is located (from Microsoft Gaming Services). It will scan the file for known keys (by SHA256 Hash) and extract any that are found.
> > Try xvdd.sys or _.dll/_.exe of GamingServices
> 
> were do i find the files?

Microsoft.GamingServices framework, it will be at a path similar to ``C:\Program Files\WindowsApps\Microsoft.GamingServices_8.71.12001.0_x64``

**Comment by UseUser123321** [comment]
> > > You misunderstand the tool.. you have to provide it a file path where _.dll/_.sys file is located (from Microsoft Gaming Services). It will scan the file for known keys (by SHA256 Hash) and extract any that are found.
> > > Try xvdd.sys or _.dll/_.exe of GamingServices
> > 
> > 
> > were do i find the files?
> 
> Microsoft.GamingServices framework, it will be at a path similar to `C:\Program Files\WindowsApps\Microsoft.GamingServices_8.71.12001.0_x64`

i already tried an other path and now worked with yours, thank you!
