### ISSUE TITLE
Impossible to extract

### ISSUE THREAD

**Issue by UseUser123321** [emoose/xvdtool#53]
I have see that system.xvd is impossible to extract, i tried everything

**Comment by Masamune3210** [comment]
Please search for issues before making a new one
https://github.com/emoose/xvdtool/issues/48

**Comment by UseUser123321** [comment]
> Please search for issues before making a new one #48

i already have see it, nobody said the solution

**Comment by tuxuser** [comment]
There is no solution other than somehow extracting the keytable from a retail console.
Nobody has been able to do so.
