### ISSUE TITLE
Xvddkeyslotutil

### ISSUE THREAD

**Issue by moti477** [emoose/xvdtool#54]
Hello.
When i use xvddkeysloutil I get this error:
[+] Ensuring previous driver instance is removed...
[+] Installing Kernel-Bridge driver...
[-] Failed to install Kernel-Bridge driver!
Last error: -2146762484
How can I fix this error?

**Comment by tuxuser** [comment]
This is the wrong repo.
As the issues are closed on XvddKeyslotUtil repo and you already figured out the right place to ask, continue there: https://github.com/HoShiMin/Kernel-Bridge/issues/48#issue-1610135382
