### ISSUE TITLE
Verifying signature throws "input too large for RSA cipher"

### ISSUE THREAD

**Issue by dragonk-m** [emoose/xvdtool#57]
I have been using xvdtool for a while and it works flawlessly, but this the first time it appears to be failing for decrypting files. I usually print package information to check I am using the right key to decrypt, and even on printing package info it fails. Debugging tells me it fails while checking for signature. Exception says "input too large for RSA cipher."

**Comment by tuxuser** [comment]
Hey, thx for the report. Could you somehow provide more metadata about the xvc container you are testing with?

Also, which RSA pubkeys are in your xvdtool folder? Please provide a file listing.

A possible workaround for the moment might be to empty out the XvdSigningKeys folder - so it does not attempt Sig verification.

**Comment by dragonk-m** [comment]
Would the ContentId or ProductId for it be enough to know which package is it?

Inside the actual xvdtool folder I have no keys, under the AppData one I have the default ones

**Comment by tuxuser** [comment]
ContentId / ProductId and filename ideally would help.

> Inside the actual xvdtool folder I have no keys, under the AppData one I have the default ones

Please provide the file structure of that folder.

Lastly, to make sure, we are talking about a MSIXVC, correct?

**Comment by tuxuser** [comment]
Was the problem solved?
